name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker images
        run: |
          # Build both services
          docker-compose build --no-cache
          
          # Tag and push FastAPI image
          docker tag fastapi_app:latest ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Starting the deploy process on EC2..."
            sudo apt-get update
            
            # Clone or update repository
            if [ ! -d "~/app" ]; then
              git clone ${{ github.server_url }}/${{ github.repository }}.git ~/app
            else
              cd ~/app && git pull origin main
            fi
            
            cd ~/app
            
            # Pull the latest FastAPI image
            echo "Pulling the latest images..."
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
            
            # Update the docker-compose.yml to use the pulled image
            sed -i "s|build: .|image: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest|g" docker-compose.yml
            
            # Restart services
            echo "Restarting services..."
            docker-compose down
            docker-compose up -d
            
            # Verify services are running
            docker-compose ps
            
            # Clean up
            echo "Cleaning up unused images..."
            docker image prune -f